_aws_ses_monitor_bounces_endpoint:
  path: /endpoint/aws/ses/notify_bounce
  defaults: { _controller: AwsSesMonitorBundle:Notify:notify }
_aws_ses_monitor_complaints_endpoint:
  path: /endpoint/aws/ses/notify_complaint
  defaults: { _controller: AwsSesMonitorBundle:Notify:notify }
_aws_ses_monitor_deliveries_endpoint:
  path: /endpoint/aws/ses/notify_delivery
  defaults: { _controller: AwsSesMonitorBundle:Notify:notify }
