_aws_ses_monitor_bounces_endpoint:
  path: /sns/bounces
  defaults: { _controller: AwsSesMonitorBundle:Bounces:bounces }
_aws_ses_monitor_complaints_endpoint:
  path: /sns/complaints
  defaults: { _controller: AwsSesMonitorBundle:Complaints:complaints }
_aws_ses_monitor_deliveries_endpoint:
  path: /sns/deliveries
  defaults: { _controller: AwsSesMonitorBundle:Deliveries:deliveries }
