---
version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30
  return-statements:
    enabled: false
plugins:
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - src/Tests/**
    checks:
      php:S1142:
        enabled: false
      php:S1172:
        enabled: false
      php:S1192:
        enabled: false
      php:S1448:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
      UnusedPrivateMethod:
        enabled: false
      UnusedLocalVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
exclude_patterns:
  - "**/Tests/"
  - "src/DependencyInjection/Configuration.php"
