---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_patterns:
  - "**/Tests/"
plugins:
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - src/Tests/**
