preset: symfony

linting: true

disabled:
- trailing_comma_in_multiline_array
- concat_without_spaces
- no_leading_import_slash
- unalign_equals
- unalign_double_arrow

enabled:
- concat_with_spaces
- align_equals
- align_double_arrow
