services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bouncesConfig: '%shq_aws_ses_monitor.bounces%'
            $complaintsConfig: '%shq_aws_ses_monitor.complaints%'
            $deliveriesConfig: '%shq_aws_ses_monitor.deliveries%'
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Service\HandlerFactory: ~
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Service\AwsClientFactory:
        arguments: ['%shq_aws_ses_monitor.aws_config%']
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Command\SesSendTestEmailsCommand: ~
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Command\SnsSetupBouncesTopicCommand:
        tags: ['shq_aws_ses_monitor.requires_credentials']
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Command\SnsSetupComplaintsTopicCommand:
        tags: ['shq_aws_ses_monitor.requires_credentials']
    SerendipityHQ\Bundle\AwsSesMonitorBundle\Command\SnsSetupDeliveriesTopicCommand:
        tags: ['shq_aws_ses_monitor.requires_credentials']
