services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $identities: '%shq_aws_ses_monitor.identities%'
            $endpointConfig: '%shq_aws_ses_monitor.endpoint%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SerendipityHQ\Bundle\AwsSesMonitorBundle\:
        resource: '../../*'
        exclude: '../../{Tests,Plugin}'

    Aws\Sns\MessageValidator: ~
