services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $config: '%shq_aws_ses_monitor.aws_config%'
            $bouncesConfig: '%shq_aws_ses_monitor.bounces%'
            $complaintsConfig: '%shq_aws_ses_monitor.complaints%'
            $deliveriesConfig: '%shq_aws_ses_monitor.deliveries%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SerendipityHQ\Bundle\AwsSesMonitorBundle\:
        resource: '../../*'

    Aws\Sns\MessageValidator: ~
